import { Device } from '../domain/device.js';

export const virtualFleet: Device[] = [
  {
    id: 'virtual-tv-001',
    kind: 'set-top-box',
    platform: 'roku',
    model:'tun-reference-low',
    virtual: true,
    performanceClass: 'low',
    capabilities: {
      resolutions: ['1080p'],
      hdrFormats: [],
      codecs: ['h264'],
      games: false,
      memoryMb: 1024,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-002',
    kind: 'set-top-box',
    platform: 'roku',
    model:'tun-reference-mid',
    virtual: true,
    performanceClass: 'mid',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc'],
      games: true,
      memoryMb: 1536,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-003',
    kind: 'set-top-box',
    platform: 'roku',
    model:'tun-reference-high',
    virtual: true,
    performanceClass: 'high',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10', 'dolby-vision'],
      codecs: ['h264', 'hevc', 'av1'],
      games: true,
      memoryMb: 2048,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-004',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-low',
    virtual: true,
    performanceClass: 'low',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc'],
      games: false,
      memoryMb: 1024,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-005',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-high',
    virtual: true,
    performanceClass: 'high',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc', 'av1'],
      games: true,
      memoryMb: 2048,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-006',
    kind: 'tv',
    platform: 'webos',
    model:'tun-reference-mid',
    virtual: true,
    performanceClass: 'mid',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['dolby-vision'],
      codecs: ['h264', 'hevc', 'av1'],
      games: true,
      memoryMb: 1536,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-007',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-low',
    virtual: true,
    performanceClass: 'low',
    capabilities: {
      resolutions: ['720p'],
      hdrFormats: [],
      codecs: ['h264'],
      games: false,
      memoryMb: 1024,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-008',
    kind: 'tv',
    platform: 'webos',
    model:'tun-reference-mid',
    virtual: true,
    performanceClass: 'mid',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc'],
      games: true,
      memoryMb: 1536,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-009',
    kind: 'tv',
    platform: 'webos',
    model:'tun-reference-high',
    virtual: true,
    performanceClass: 'high',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10', 'dolby-vision'],
      codecs: ['h264', 'hevc', 'av1'],
      games: true,
      memoryMb: 2048,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-010',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-low',
    virtual: true,
    performanceClass: 'low',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc'],
      games: false,
      memoryMb: 1024,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-011',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-high',
    virtual: true,
    performanceClass: 'high',
    capabilities: {
      resolutions: ['2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc', 'av1'],
      games: true,
      memoryMb: 2048,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-012',
    kind: 'tv',
    platform: 'webos',
    model:'tun-reference-mid',
    virtual: true,
    performanceClass: 'mid',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['dolby-vision'],
      codecs: ['h264', 'hevc', 'av1'],
      games: true,
      memoryMb: 1536,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-013',
    kind: 'set-top-box',
    platform: 'roku',
    model:'tun-reference-low',
    virtual: true,
    performanceClass: 'low',
    capabilities: {
      resolutions: ['720p'],
      hdrFormats: [],
      codecs: ['hevc'],
      games: false,
      memoryMb: 1024,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-014',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-mid',
    virtual: true,
    performanceClass: 'mid',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc'],
      games: true,
      memoryMb: 1536,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-015',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-high',
    virtual: true,
    performanceClass: 'high',
    capabilities: {
      resolutions: ['1080p', '2160p', '4320p'],
      hdrFormats: ['hdr10+', 'dolby-vision'],
      codecs: ['h264', 'hevc'],
      games: true,
      memoryMb: 2048,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
  {
    id: 'virtual-tv-016',
    kind: 'tv',
    platform: 'tizen',
    model:'tun-reference-mid',
    virtual: true,
    performanceClass: 'mid',
    capabilities: {
      resolutions: ['1080p', '2160p'],
      hdrFormats: ['hdr10'],
      codecs: ['h264', 'hevc'],
      games: true,
      memoryMb: 1536,
    },
    supportedOperations: [
      'device/info',
      'operations/list',
      'health-check/get',
      'applications/launch',
    ],
    status: 'available',
    consecutiveInfrastructureFailures: 0
  },
];